#!/bin/bash

cd $LIODIR_IMAGES
hsetroot -solid '#000000' 

llw --send-stop
sleep 0.4

if [ $# -eq 2 ]; then
  descr="$2"
  descr=${descr//\//}
  case "$1" in 
    'v')  decr="$(find ./VIDEOS -name *$descr* | head -n1)"
          flags="-v"
      ;;
    'g')  decr="$(find ./GISS   -name *$descr* | head -n1)"
          flags="-v"
      ;;
    'd')  decr="$(cat Descriptors.maww | grep $descr | head -n1 | awk '{print $2}')"
          flags="-f Descriptors.maww -i"
      ;;
  esac
  echo "Descriptor: $decr"
else
  find_args=()
  excext=(txt liotree)
  for ext in "${excext[@]}"; do
    find_args+=( -not -iname "*.${ext}" )
  done
  # Random number between 0 and 1
  case "$((RANDOM % 3))" in
    "0")
      decr="$(shuf -n1 Descriptors.maww | awk '{print $2}')"
      flags="-f Descriptors.maww -i"
      ;;
    "1")
      decr="$(find ./GIFS -maxdepth 1 -type f -print0 "${find_args[@]}" | shuf -z -n1 | tr -d '\0')"
      flags="-v"
    ;;
    "2")
      decr="$(find ./VIDEOS -maxdepth 1 -type f -print0 "${find_args[@]}" | shuf -z -n1 | tr -d '\0')"
      flags="-v"
    ;;
  esac
  echo "Descriptor: $decr"
fi
llw -F --send-stop $flags "$decr" >> /tmp/lovdog_live_wallpaper.log 2>&1 &

