#!/bin/bash

## Archivo de CAVA (si se cambia en el código fuente, cambiar también aquí)
cava_fifo="/tmp/lovdog_live_wallpaper/cava_fifo"
config_file="/tmp/lovdog_live_wallpaper_cava_config"
cava_fps=30
cava_num_bars=85
cava_bars_height=0.7
llw_widgets="$LIODIR_IMAGES/LovdogLiveWallpaper/widgets/"
llw_widget="$llw_widgets/cal_todo.sh"
wallpapers_slideshow_dir="$HOME/.WallPapers"

pkill cava

# write cava config
echo "
[general]
bars = ${cava_num_bars}
sleep_timer = 0       # Reduce latencia
autosens = 0.3
mode = single
sensitivity = 130

[smoothing]
gravity = 421
integral = 0.1
monstercat=1
waves = 0

[input]
method = pipewire
source = auto
framerate = ${cava_fps}

[output]
channels = mono
method = raw
data_format = binary
bit_format = 8bit
" > $config_file

rm -f $cava_fifo
mkfifo $cava_fifo

# start cava instance
cava -p $config_file > $cava_fifo 2>/dev/null &

###### ARRANCADOR NORMAL

if [ $# -eq 1 ]; then 
  exit 0
fi

cd $LIODIR_IMAGES
#pkill get_widget_data
rm /tmp/lovdog_live_wallpaper/widgets_continue
LovdogLiveWallpaper/widgets/get_widget_data > $HOME/.log/lovdog_live_wallpaper_get_widget_data.log 2>&1 &
llw --send-stop
sleep 0.9

if [ $# -eq 2 ]; then
  descr="$2"
  descr=${descr//\//}
  case "$1" in 
    'v')  decr="$(find ./VIDEOS -name "*$descr*" | head -n1)"
          flags="-v"
      ;;
    'g')  decr="$(find ./GIFS   -name "*$descr*" | head -n1)"
          flags="-v"
      ;;
    'd')  decr="$(cat Descriptors.maww | grep $descr | head -n1 | awk '{print $2}')"
          flags="-f Descriptors.maww -i"
      ;;
  esac
  echo "Descriptor: $decr"
else
  find_args=()
  excext=(txt liotree)
  for ext in "${excext[@]}"; do
    find_args+=( -not -iname "*.${ext}" )
  done
  # Random number between 0 and 1
  case "$((1 + (RANDOM % 2)))" in
    "0")
      decr="$(shuf -n1 Descriptors.maww | awk '{print $2}')"
      flags="-f Descriptors.maww -i"
      ;;
    "1")
      decr="$(find ./GIFS -maxdepth 1 -type f -print0 "${find_args[@]}" | shuf -z -n1 | tr -d '\0')"
      flags="-v"
    ;;
    "2")
      decr="$(find ./VIDEOS -maxdepth 1 -type f -print0 "${find_args[@]}" | shuf -z -n1 | tr -d '\0')"
      flags="-v"
    ;;
  esac
  echo "Descriptor: $decr"
fi

llw -w "." -L -1 -X 10 -M 'BigBlueTermPlus Nerd Font' -  --cava -F -H $cava_bars_height -B $cava_num_bars -Z $cava_fps --send-stop -D 1300 -T 200 $flags "$decr" >> $HOME/.log/lovdog_live_wallpaper.log 2>&1 &
#llw -w "." -L -1 -X 10 -M 'BigBlueTermPlus Nerd Font' - --cava -K '#ff0000:#0000ff' -F -H $cava_bars_height -B $cava_num_bars -Z $cava_fps --send-stop $flags "$decr" >> $HOME/.log/lovdog_live_wallpaper.log 2>&1 &
#llw -w "." -X 10 -M 'BigBlueTermPlus Nerd Font' --cava -A -F -H $cava_bars_height -B $cava_num_bars -Z $cava_fps --send-stop $flags "$decr" > /tmp/lovdog_live_wallpaper.log 2>>&1 &

