#!/bin/bash


cd $(dirname "${BASH_SOURCE[0]}")

widget_prefix='/tmp/lovdog_live_wallpaper_widget'
while [ 1 ]; do
  khal calendar  --format "{start-time} {title}" now 7d > ${widget_prefix}_khal &
  todo > ${widget_prefix}_todo &
  WTTR="$(curl 'wttr.in/?T&2')"
  echo "$WTTR" > ${widget_prefix}_wttr1
  ./get_wttr
  ./llw-sensors > ${widget_prefix}_sensors
  sleep 8s
done
